#!/usr/local/bin/python
"""
Print out MFA keys from an age-encrypted file. Optionally generate QR codes for them

Single-entry output:
>>> output = make_output("alpha")
>>> True if re.match(r'^[0-9]{6}$', output) else output
True

Multi-entry output:
>>> output = make_output("beta")
>>> True if re.match(r'^beta [0-9]{6}\\nsecond-beta [0-9]{6}\\n$', output) else output
True

No-entry output:
>>> make_output("nothing")
''
>>> make_output("nothing", qr_code=True)
''

Exact match:
>>> output = make_output("beta", exact = True)
>>> True if re.match(r'^[0-9]{6}$', output) else output
True

Single-entry XML output
>>> make_output("alpha", True) # doctest:+ELLIPSIS
'<?xml version="1.0"?>\\n<items>\\n  <item uid="alpha" arg="alpha" valid="yes">\\n    <title>alpha ...</title>\\n    <subtitle>OTP target</subtitle>\\n  </item>\\n</items>\\n'

Multi-entry XML output
>>> make_output("beta", True) # doctest:+ELLIPSIS
'<?xml version="1.0"?>\\n<items>\\n  <item uid="beta" arg="beta" valid="yes">\\n    <title>beta ...</title>\\n    <subtitle>OTP target</subtitle>\\n  </item>\\n  <item uid="second-beta" arg="second-beta" valid="yes">\\n    <title>second-beta ...</title>\\n    <subtitle>OTP target</subtitle>\\n  </item>\\n</items>\\n'

To run the above, run `otp -t [-v]`
"""

import sys, re, subprocess
import pyotp
from subprocess import check_output, CalledProcessError
from os.path import expanduser
from pyrage import decrypt, ssh, x25519
import argparse
import qrcode
from io import StringIO
homedir = expanduser("~")
KEYFILE = "%s/.sec/otp.age" % homedir

def format_otp(tag, secret):
  return (tag, pyotp.totp.TOTP(secret).now(), secret)

def find_entries(filter_term, exact = False):
  output = []
  cmd = ['age', '-d', '-i', '/Users/allen/.ssh/bale', KEYFILE]
  data = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, input=b'').stdout
  lines = data.rstrip().split(b'\n')
  for i, l in enumerate(lines, 1):
    line = l.decode('utf-8')
    if line[0] == '#':
      continue
    (tag, key) = re.split('\s+', line)
    if exact and tag == filter_term:
      return [format_otp(tag, key)]
    try:
      if tag.find(filter_term) < 0:
        continue
    except NameError:
      pass
    output.append(format_otp(tag, key))
  return output

xml_template = {
  "head": """<?xml version="1.0"?>
<items>
""",
  "item": """  <item uid="{0}" arg="{0}" valid="yes">
    <title>{0} {1}</title>
    <subtitle>OTP target</subtitle>
  </item>
""",
  "foot": "</items>\n"
}

def make_output(filter_term, xml = False, exact = False, qr_code = False):
  entries = find_entries(filter_term, exact)
  cap = StringIO()
  if xml:
    cap.write(xml_template["head"])
    for tag, key, _ in entries:
      cap.write(xml_template["item"].format(tag, key))
    cap.write(xml_template["foot"])
  else:
    for tag, key, secret in entries:
      if len(entries) == 1:
        cap.write(key)
      else:
        cap.write('%s %s\n' % (tag, key))
      if qr_code:
        qr = qrcode.QRCode()
        tag="Ice Cream Social"
        qr.add_data("otpauth://totp/%s?secret=%s" % (tag, secret))
        qr.print_ascii(cap)
  return cap.getvalue()

def test(args):
  """Uses a fixed keyfile to match test assumptions. Still requires
  that the file be decrypted by a key in the current user's GPG agent.
  Decrypted file contents:
  alpha DXGB265VIPTKJJAY
  beta HWLQWPRTFVCZRKNZ
  second-beta ACFBSDJG5UIPXEM4
  """
  global KEYFILE
  import doctest, tempfile, base64, os
  tmp = tempfile.NamedTemporaryFile(delete=False)
  try:
    tmp.write(base64.b64decode("hQEMA/S91YFMxGy0AQf/Q56FAICNtMKOv/n/BAK5wg7vvZ85fdLGapx25S/UywtnOsgCr5OKklEUDTiVMO1nUJsA0z/3DUwk0z/NKSwJDged5y2fr/+7tT4ObS2byNoX5Fcz00iAGZR1HfAWzXLO0RF4WuFGWu550Pvo93qmvirU/L7z2lD2KGulkEfV7Gs94v45BQqYD44ZIom271/htp61yLI/GlrYXYdU7TgXToUaxBXZoGDhb/PT7DrTsEFZ8PFgD4l/cDx3ikA+4U5gzPyNK6viFgbDY6hrlW/hvfPiOrtwqEsYXRqE2/TmNe1VrqbPUQzxfvjmosC1gXp4ypu1XcyGScfahsqILzxg39KCAb3+ULSwQhBQBfJru0dNGbaF/crgrbYkIQjta3avrZEl20+bixI7iw8Z8dju+pPk5LXaF0q2dIvIiPqobWjNJkvauFhliBsrJg+viyX0xx6o+SpqMCJaMs4BCJFsJtaGCSfNr9mkbkiwWVSyGwr6L7qF2y29aPuCVcD1im4IP/LqUA=="))
    KEYFILE = tmp.name
    tmp.close()
    result = doctest.testmod(verbose = args.verbose, exclude_empty = True)
    if result.failed == 0:
      print(f'{result.attempted} successful tests')
  finally:
    os.unlink(tmp.name)

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('term',  nargs='?', default='', help='Search term for finding the relevant key(s)')
  group = parser.add_mutually_exclusive_group()
  group.add_argument('-q', '--qr_code', help='produce a QR code for the found key(s)', action='store_true')
  group.add_argument('-x', '--xml', help='Output XML for option enumeration by Alfred 3', action='store_true')
  parser.add_argument('-e', '--exact', help="Match must be exact, don't search substrings.", action='store_true')
  parser.add_argument('-t', '--test', help="Run doctests", action='store_true')
  parser.add_argument('-v', '--verbose', help="Run doctests verbosely", action='store_true')
  args = parser.parse_args()
  if args.test:
    test(args)
  else:
    sys.stdout.write(make_output(args.term, args.xml, args.exact, args.qr_code))

if __name__ == "__main__":
  main()
